Repository mlange-42/arche, pull requests merged in 2024-03, with the labels that each got.

#408 Add entity read access
  ecs/entity.go
  ecs/entity_test.go
Labels: usability

#409 Linter: mask unused arguments by assigning to blank
  CHANGELOG.md
  ecs/query.go
  ecs/world_internal.go
Labels: internal

#411 Add a showcase chapter "Made with Arche" to the documentation page
  CHANGELOG.md
  docs/content/made_with/_index.md
  docs/hugo.toml
  docs/layouts/partials/custom-header.html
  docs/layouts/shortcodes/card.html
  docs/layouts/shortcodes/row.html
  docs/static/css/cards.css
  docs/static/css/style.css
Labels: documentation
